version: '3.9'

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    image: community-api:latest
    container_name: api
    ports:
      - '3001:3001'
    environment:
      - NODE_ENV=production
    networks:
      - app-network

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: community-client:latest
    container_name: client
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
    networks:
      - app-network

networks:
  app-network:
    name: app-network
