name: Deploy to Firebase Hosting on merge

"on":
    push:
        branches:
            - main

jobs:
    build_and_deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 16

            - name: Install dependencies and build API
              run: |
                  cd api
                  npm ci
                  cd ..

            - name: Install dependencies and build Client
              run: |
                  cd client
                  npm ci
                  npm run build
                  cd ..

            - name: Deploy to Firebase Hosting
              uses: FirebaseExtended/action-hosting-deploy@v0
              with:
                  repoToken: "${{ secrets.GITHUB_TOKEN }}"
                  firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_COMMUNITY_9EEF4 }}"
                  channelId: live
                  projectId: community-9eef4

            - name: Deploy to Firebase Functions
              run: |
                  cd api
                  npm run deploy
                  cd ..
              env:
                  FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_COMMUNITY_9EEF4 }}
